# ambivo_agents_config_sample.py
"""
Dedicated configuration file for Ambivo Agents
Converted from agent_config.yaml for Flask integration

INSTRUCTIONS:
1. Copy this file to your Flask project directory
2. Replace ALL placeholder values with your actual credentials
3. Add 'ambivo_agents_config.py' to your .gitignore file
4. For production, consider using environment variables instead
"""

# ========== REDIS CONFIGURATION ==========
AMBIVO_AGENTS_REDIS_HOST = "your-redis-host.redis.cloud"
AMBIVO_AGENTS_REDIS_PORT = 6379
AMBIVO_AGENTS_REDIS_PASSWORD = "your-redis-password"
AMBIVO_AGENTS_REDIS_DB = 0

# ========== LLM CONFIGURATION ==========
AMBIVO_AGENTS_OPENAI_API_KEY = "your-openai-api-key"
AMBIVO_AGENTS_ANTHROPIC_API_KEY = "your-anthropic-api-key"
AMBIVO_AGENTS_AWS_ACCESS_KEY_ID = "your-aws-access-key-id"
AMBIVO_AGENTS_AWS_SECRET_ACCESS_KEY = "your-aws-secret-access-key"
AMBIVO_AGENTS_AWS_REGION = "us-east-1"
AMBIVO_AGENTS_VOYAGE_API_KEY = "your-voyage-api-key"
AMBIVO_AGENTS_PREFERRED_PROVIDER = "openai"
AMBIVO_AGENTS_TEMPERATURE = 0.5
AMBIVO_AGENTS_MAX_TOKENS = 4000

# ========== AGENT CAPABILITIES ==========
AMBIVO_AGENTS_ENABLE_KNOWLEDGE_BASE = True
AMBIVO_AGENTS_ENABLE_WEB_SEARCH = True
AMBIVO_AGENTS_ENABLE_CODE_EXECUTION = True
AMBIVO_AGENTS_ENABLE_FILE_PROCESSING = True
AMBIVO_AGENTS_ENABLE_WEB_INGESTION = True
AMBIVO_AGENTS_ENABLE_API_CALLS = True
AMBIVO_AGENTS_ENABLE_WEB_SCRAPING = True
AMBIVO_AGENTS_ENABLE_PROXY_MODE = True
AMBIVO_AGENTS_ENABLE_MEDIA_EDITOR = True
AMBIVO_AGENTS_ENABLE_YOUTUBE_DOWNLOAD = True

# ========== WEB SEARCH CONFIGURATION ==========
AMBIVO_AGENTS_BRAVE_API_KEY = "your-brave-api-key"
AMBIVO_AGENTS_AVESAPI_API_KEY = "your-aves-api-key"
AMBIVO_AGENTS_WEB_SEARCH_MAX_RESULTS = 10
AMBIVO_AGENTS_WEB_SEARCH_TIMEOUT = 10
AMBIVO_AGENTS_WEB_SEARCH_SAFE_SEARCH = "moderate"
AMBIVO_AGENTS_WEB_SEARCH_COUNTRY = "US"
AMBIVO_AGENTS_WEB_SEARCH_LANGUAGE = "en"

# ========== KNOWLEDGE BASE CONFIGURATION ==========
AMBIVO_AGENTS_QDRANT_URL = "https://your-cluster-id.us-east4-0.gcp.cloud.qdrant.io:6333"
AMBIVO_AGENTS_QDRANT_API_KEY = "your-qdrant-api-key"
AMBIVO_AGENTS_KB_MAX_FILE_SIZE_MB = 50
AMBIVO_AGENTS_KB_CHUNK_SIZE = 1024
AMBIVO_AGENTS_KB_CHUNK_OVERLAP = 20
AMBIVO_AGENTS_KB_SIMILARITY_TOP_K = 5
AMBIVO_AGENTS_KB_VECTOR_SIZE = 1536
AMBIVO_AGENTS_KB_DISTANCE_METRIC = "cosine"
AMBIVO_AGENTS_DEFAULT_COLLECTION_PREFIX=""

# ========== YOUTUBE DOWNLOAD CONFIGURATION ==========
AMBIVO_AGENTS_YOUTUBE_DOCKER_IMAGE = "sgosain/amb-ubuntu-python-public-pod"
AMBIVO_AGENTS_YOUTUBE_DOWNLOAD_DIR = "./youtube_downloads"
AMBIVO_AGENTS_YOUTUBE_TIMEOUT = 600
AMBIVO_AGENTS_YOUTUBE_MEMORY_LIMIT = "1g"
AMBIVO_AGENTS_YOUTUBE_DEFAULT_AUDIO_ONLY = True

# ========== MEDIA EDITOR CONFIGURATION ==========
AMBIVO_AGENTS_MEDIA_DOCKER_IMAGE = "sgosain/amb-ubuntu-python-public-pod"
AMBIVO_AGENTS_MEDIA_INPUT_DIR = "./examples/media_input"
AMBIVO_AGENTS_MEDIA_OUTPUT_DIR = "./examples/media_output"
AMBIVO_AGENTS_MEDIA_TEMP_DIR = "/tmp/media_editor"
AMBIVO_AGENTS_MEDIA_TIMEOUT = 300
AMBIVO_AGENTS_MEDIA_MAX_FILE_SIZE_GB = 5
AMBIVO_AGENTS_MEDIA_MEMORY_LIMIT = "2g"
AMBIVO_AGENTS_MEDIA_FFMPEG_THREADS = 4
AMBIVO_AGENTS_MEDIA_DEFAULT_VIDEO_CODEC = "h264"
AMBIVO_AGENTS_MEDIA_DEFAULT_AUDIO_CODEC = "aac"

# ========== WEB SCRAPING CONFIGURATION ==========
AMBIVO_AGENTS_WEB_SCRAPING_DOCKER_IMAGE = "sgosain/amb-ubuntu-python-public-pod"
AMBIVO_AGENTS_WEB_SCRAPING_PROXY_ENABLED = True
AMBIVO_AGENTS_WEB_SCRAPING_PROXY_HTTP = "http://scraperapi:your-scraperapi-key@proxy-server.scraperapi.com:8001"
AMBIVO_AGENTS_WEB_SCRAPING_TIMEOUT = 120
AMBIVO_AGENTS_WEB_SCRAPING_RATE_LIMIT = 2.0
AMBIVO_AGENTS_WEB_SCRAPING_MAX_CONCURRENT = 2
AMBIVO_AGENTS_WEB_SCRAPING_MEMORY_LIMIT = "2g"

# ========== DOCKER CONFIGURATION ==========
AMBIVO_AGENTS_DOCKER_MEMORY_LIMIT = "512m"
AMBIVO_AGENTS_DOCKER_TIMEOUT = 60
AMBIVO_AGENTS_DOCKER_WORK_DIR = "/opt/ambivo/work_dir"

# ========== MODERATOR CONFIGURATION ==========
AMBIVO_AGENTS_MODERATOR_ENABLED_AGENTS = "knowledge_base,web_search,assistant,media_editor,youtube_download,code_executor,web_scraper"
AMBIVO_AGENTS_MODERATOR_CONFIDENCE_THRESHOLD = 0.6
AMBIVO_AGENTS_MODERATOR_ENABLE_MULTI_AGENT = True
AMBIVO_AGENTS_MODERATOR_FALLBACK_AGENT = "assistant"
AMBIVO_AGENTS_MODERATOR_MAX_ROUTING_ATTEMPTS = 3
AMBIVO_AGENTS_MODERATOR_MAX_CONCURRENT_AGENTS = 3
AMBIVO_AGENTS_MODERATOR_TIMEOUT_SECONDS = 30

# ========== SERVICE CONFIGURATION ==========
AMBIVO_AGENTS_LOG_LEVEL = "INFO"
AMBIVO_AGENTS_LOG_TO_FILE = True
AMBIVO_AGENTS_ENABLE_METRICS = True
AMBIVO_AGENTS_MAX_SESSIONS = 100
AMBIVO_AGENTS_SESSION_TIMEOUT = 3600

# ========== MEMORY MANAGEMENT ==========
AMBIVO_AGENTS_MEMORY_COMPRESSION_ENABLED = True
AMBIVO_AGENTS_MEMORY_COMPRESSION_ALGORITHM = "lz4"
AMBIVO_AGENTS_MEMORY_CACHE_ENABLED = True
AMBIVO_AGENTS_MEMORY_CACHE_MAX_SIZE = 1000
AMBIVO_AGENTS_MEMORY_CACHE_TTL = 300

# ========== PERFORMANCE LIMITS ==========
AMBIVO_AGENTS_MAX_CONCURRENT_OPERATIONS = 5
AMBIVO_AGENTS_OPERATION_TIMEOUT_SECONDS = 30
AMBIVO_AGENTS_MAX_MEMORY_USAGE_MB = 500